version: '1'

services:
  mysql-standalone:
    image: mysql:latest

      environment:
        - MYSQL_ROOT_PASSWORD=admin123
        - MYSQL_DATABASE=test
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=testuser@123

      ports:
        - 3306:3306

      springboot-docker-container:
        image:springboot-docker-container
        container_name:springboot-docker-container
        restart: on-failure
        ports:
          -8080:8080
        build:
          context: ./
          dockerfile:Dockerfile
        depends_on:
          - mysql-standalone